
export const GENRES = [
    'High Fantasy',
    'Sci-Fi',
    'Cyberpunk',
    'Steampunk',
    'Urban Fantasy',
    'Gothic Horror',
    'Post-Apocalyptic',
    'Historical Fiction',
    'Modern Slice of Life',
    'Space Opera',
    'Isekai',
    'LitRPG',
    'Wuxia',
    'Noir',
    'Psychological Thriller',
    'Cosmic Horror',
    'Military Sci-Fi',
];

export const STYLES = [
    'Gritty & Realistic',
    'Anime / Manga',
    'Heroic & Epic',
    'Dark & Melancholic',
    'Whimsical & Lighthearted',
    'Mysterious & Eldritch',
    'Cinematic & Dramatic',
    'Comedic & Absurd',
    'Tarantino-esque',
    'Sorkin-esque Dialogue',
    'Studio Ghibli-esque',
    'Lovecraftian',
    'Shounen Manga',
    'Slice-of-Life Anime',
    'Tolkien-esque Epic',
];

export const AUTHORS = [
    'Party Girl',
    'Sweetheart',
    'Iron Sculptor',
    'Existential Curator',
    'Detonationist',
    'Corpse Narrator',
    'Glacial Observer',
    'Spiky Rose',
    'Whispering Petal',
    'Dungeon Heart',
    'Yandere',
    'Goth',
    'Gooner',
    'Isekai Chronicler',
    'Shounen Enthusiast',
    'Dialogue Dynamo',
    'Dream Weaver',
    'Lore Master',
    'Abyssal Scribe',
];

export const EXPRESSIONS = [
    'admiration', 'amusement', 'anger', 'annoyance', 'approval', 'caring', 'confusion',
    'curiosity', 'desire', 'disappointment', 'disapproval', 'disgust', 'embarrassment',
    'excitement', 'fear', 'gratitude', 'grief', 'joy', 'love', 'nervousness',
    'neutral', 'optimism', 'pride', 'realization', 'relief', 'remorse', 'sadness', 'surprise',
];