export const NEMO_EXTENSION_CATALOG = Object.freeze([
    Object.freeze({
        id: 'NemoPromptTools',
        name: 'Nemo Prompt Tools',
        repository: 'https://github.com/NemoVonNirgend/NemoPromptTools',
        description: 'Preset and character navigation, prompt browsers, and improved reasoning workflow tools.',
        category: 'Prompt Tools',
        icon: 'fa-solid fa-list-check',
        recommended: true,
        requiresReload: true,
    }),
    Object.freeze({
        id: 'NemoUIOverhaul',
        name: 'Nemo UI Overhaul',
        repository: 'https://github.com/NemoVonNirgend/NemoUIOverhaul',
        description: 'Optional backgrounds, settings, connection, lorebook, navigation, mobile, and model-selection UI improvements.',
        category: 'UI & Themes',
        icon: 'fa-solid fa-wand-magic-sparkles',
        recommended: false,
        requiresReload: true,
    }),
    Object.freeze({
        id: 'NemoEmojiPicker',
        name: 'Nemo Emoji Picker',
        repository: 'https://github.com/NemoVonNirgend/NemoEmojiPicker',
        description: 'A searchable emoji picker for the SillyTavern message composer.',
        category: 'Composer Tools',
        icon: 'fa-regular fa-face-smile',
        recommended: false,
        requiresReload: true,
    }),
    Object.freeze({
        id: 'NemoImageGeneration',
        name: 'Nemo Image Generation',
        repository: 'https://github.com/NemoVonNirgend/NemoImageGeneration',
        description: 'Automatic Pollinations image detection and generation using SillyTavern image providers.',
        category: 'Image Generation',
        icon: 'fa-regular fa-image',
        recommended: false,
        requiresReload: true,
    }),
    Object.freeze({
        id: 'NemoLore',
        name: 'NemoLore',
        repository: 'https://github.com/NemoVonNirgend/NemoLore',
        description: 'Long-form roleplay memory, summaries, semantic retrieval, and lore maintenance.',
        category: 'Memory & Lore',
        icon: 'fa-solid fa-brain',
        recommended: true,
        requiresReload: true,
    }),
    Object.freeze({
        id: 'Ember',
        name: 'Ember',
        repository: 'https://github.com/NemoVonNirgend/Ember',
        description: 'Interactive JavaScript, rendered HTML, and reusable chat artifacts.',
        category: 'Interactive Content',
        icon: 'fa-solid fa-fire-flame-curved',
        recommended: true,
        requiresReload: true,
    }),
    Object.freeze({
        id: 'NemoGuides',
        name: 'Nemo Guides',
        repository: 'https://github.com/NemoVonNirgend/NemoGuides',
        description: 'Optional scene assessment, planning, writing, DM notes, rules, and narrative utility tools.',
        category: 'Narrative Tools',
        icon: 'fa-solid fa-compass-drafting',
        recommended: false,
        requiresReload: true,
    }),
    Object.freeze({
        id: 'NemoRewrite',
        name: 'Nemo Rewrite',
        repository: 'https://github.com/NemoVonNirgend/NemoRewrite',
        description: 'Selection-based rewriting, shortening, expansion, custom editing, deletion, undo, and optional NemoLore preference evidence.',
        category: 'Writing Tools',
        icon: 'fa-solid fa-wand-magic-sparkles',
        recommended: false,
        requiresReload: true,
    }),
]);

export function findCatalogEntry(id) {
    return NEMO_EXTENSION_CATALOG.find(entry => entry.id === id) ?? null;
}
